name: Security Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # 毎週日曜日の00:00 UTC

jobs:
  security-audit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run npm audit
        run: |
          npm audit --json > audit-results.json || true
          npm audit || true
          
      - name: Check audit results
        run: |
          if [ -f audit-results.json ]; then
            high_vulns=$(cat audit-results.json | jq -r '.metadata.vulnerabilities.high // 0')
            critical_vulns=$(cat audit-results.json | jq -r '.metadata.vulnerabilities.critical // 0')
            
            if [ "$critical_vulns" -gt 0 ] || [ "$high_vulns" -gt 0 ]; then
              echo "Found $critical_vulns critical and $high_vulns high vulnerabilities"
              exit 1
            fi
          fi
          
      - name: Upload audit results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: audit-results
          path: audit-results.json
          
      - name: Run ESLint security checks
        run: npm run lint
        
      - name: Type check
        run: npm run type-check

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: moderate